### ISSUE TITLE
socat.ps1 没找到，能否提供下

### ISSUE THREAD

**Issue by brucmao** [escape0707/markdown-practice#25]
```
$Startup = [Environment]::GetFolderPath('Startup')
$WshShell = New-Object -comObject WScript.Shell
$Shortcut = $WshShell.CreateShortcut("$Startup\Run Socat.lnk")
$Shortcut.TargetPath = "powershell.exe"
$Shortcut.Arguments = "-File `"C:\Users\tothe\my-programs\dotfiles\socat.ps1`""
$Shortcut.WorkingDirectory = "C:\Users\tothe\my-programs\socat"
$Shortcut.Save()
```
上面这段powershell脚本是创建socat快捷启动方式把，能否提供下socat.ps1 这个脚本

**Comment by escape0707** [comment]
https://github.com/escape0707/olddotfiles/blob/master/socat.ps1

我改了repo名了，这边忘了改了（因为已经不用WSL，完全切回到Arch了

**Comment by escape0707** [comment]
不知道权限方面是否能被公开访问（

**Comment by escape0707** [comment]
回顾了一下原issue，我现在觉得后面人提的脚本改hosts、mDNS、ssh隧道的方法看来都不错。总之建议你也看一下原帖。

**Comment by brucmao** [comment]
请问下用socat目的是什么，感觉用clash，可以直接在wsl2中设置代理把
```
export all_proxy="socks5://${hostip}:7890"
```

**Comment by escape0707** [comment]
现在可能有hostip这个变量了，之前我用的时候是没有的

**Comment by brucmao** [comment]
hostip是可以从/etc/resolv.conf 获得
https://solidspoon.xyz/2021/02/17/%E9%85%8D%E7%BD%AEWSL2%E4%BD%BF%E7%94%A8Windows%E4%BB%A3%E7%90%86%E4%B8%8A%E7%BD%91/

**Comment by escape0707** [comment]
嗯，这也是一种方法，您可以选择这个方法，或者我提到的issue里面的其他类似的获取宿主机ip的方法，本质是一样的。

这个socat和ssh隧道算是另一种方法，只要能达到您的目的，选择什么方法都可以。
